openapi: 3.0.1
info:
  title: Store Service
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
security: []
tags:
  - name: public
paths:
  /store/api/public/v1/orders:
    get:
      tags:
        - public
      summary: Получить список заказов пользователя
      operationId: orders
      responses:
        "200":
          description: Список заказов пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - TokenBasedAuth: []
      x-handler-args:
        - field: authenticationToken
          type: org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken
          optional: true
  /store/api/public/v1/orders/{orderUid}:
    get:
      tags:
        - public
      summary: Получить подробную информацию о заказе
      operationId: orderByUid
      parameters:
        - name: orderUid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Подробная информация о заказе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedOrderResponse'
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - TokenBasedAuth: []
      x-handler-args:
        - field: authenticationToken
          type: org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken
          optional: true
  /store/api/public/v1/orders/{orderUid}/cancel:
    delete:
      tags:
        - public
      summary: Отменить заказ
      operationId: cancel
      parameters:
        - name: orderUid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "202":
          description: Заказ отменен
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - TokenBasedAuth: []
      x-handler-args:
        - field: authenticationToken
          type: org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken
          optional: true
  /store/api/public/v1/orders/{orderUid}/warranty:
    post:
      tags:
        - public
      summary: Запросить гарантию по заказу
      operationId: warranty
      parameters:
        - name: orderUid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        "200":
          description: Информация о статусе гарантии
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarrantyResponse'
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - TokenBasedAuth: []
      x-handler-args:
        - field: authenticationToken
          type: org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken
          optional: true
  /store/api/public/v1/orders/purchase:
    post:
      tags:
        - public
      summary: Выполнить заказ
      operationId: purchase
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        "201":
          description: Заказ создан
          headers:
            Location:
              description: Ссылка на созданный заказ
              style: simple
              schema:
                type: string
        "400":
          description: Ошибка входных данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Товар недоступен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - TokenBasedAuth: []
      x-handler-args:
        - field: authenticationToken
          type: org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken
          optional: true
  /warehouse/api/public/v1/items:
    get:
      tags:
        - public
      summary: Получить все доступные товары
      operationId: availableItems
      responses:
        "200":
          description: Информация о доступных товарах
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemInfo'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
      additionalProperties: false
    OrderResponse:
      type: object
      properties:
        orderUid:
          type: string
          format: uuid
        userId:
          type: string
        status:
          $ref: '#/components/schemas/OrderStatus'
        orderDate:
          type: string
          format: date-time
        items:
          type: array
          items:
            type: string
      additionalProperties: false
      example:
        orderUid: d3795a76-d514-4db7-90d1-173e7e49aedb
        userId: romanow
        status: PROCESSED
        orderDate: 2025-05-05T10:00:00Z
        items:
          - Lego 8880
    DetailedOrderResponse:
      type: object
      additionalProperties: false
      example:
        orderUid: d3795a76-d514-4db7-90d1-173e7e49aedb
        userId: romanow
        status: PROCESSED
        orderDate: 2025-05-05T10:00:00Z
        items:
          - name: Lego 8880
            description: Lego Technic Supercar 8880
            manufacturer: Lego
            imageUrl: https://main-cdn.sbermegamarket.ru/big2/lego-8880.jpg
            warranty:
              name: Lego 8880
              status: ON_WARRANTY
              comment: ""
              warrantyStartDate: 2025-05-05T10:00:00Z
              lastUpdateDate: 2025-05-05T10:00:00Z
      allOf:
        - $ref: '#/components/schemas/OrderResponse'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/ItemInfo'
    WarrantyResponse:
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/WarrantyStatus'
        comment:
          type: string
          nullable: true
      additionalProperties: false
      example:
        name: Lego 8880
        status: TAKE_NEW
        comment: Take new item from Warehouse
    OrderStatus:
      type: string
      additionalProperties: false
      enum:
        - PROCESSED
        - CANCELED
    WarrantyStatus:
      type: string
      additionalProperties: false
      enum:
        - ON_WARRANTY
        - TAKE_NEW
        - REPAIR
        - REMOVED_FROM_WARRANTY
    ItemInfo:
      type: object
      properties:
        name:
          type: string
        count:
          type: integer
          format: int32
        description:
          type: string
          nullable: true
        manufacturer:
          type: string
          nullable: true
        imageUrl:
          type: string
          format: url
          nullable: true
      additionalProperties: false
      example:
        name: Lego 8880
        count: 1
        description: Lego Technic Supercar 8880
        manufacturer: Lego
        imageUrl: https://main-cdn.sbermegamarket.ru/big2/lego-8880.jpg
  securitySchemes:
    TokenBasedAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
